# mkdocs.yml
site_name: RaspberryPier
site_url: https://SwartzMss.github.io/RaspberryPier/
site_description: RaspberryPi 5 学习笔记

docs_dir: docs

theme:
  name: readthedocs

nav:
  - 首页: index.md
  - 树莓派专用命令: commands.md
  - GPIO 操作指南: gpio.md
  - 网络配置: network.md
  - 传感器: sensors.md
  - 系统优化: system_optimization.md
