# mkdocs.yml
site_name: RaspberryPier
site_url: https://SwartzMss.github.io/RaspberryPier/
site_description: RaspberryPi 5 学习笔记

docs_dir: docs

theme:
  name: readthedocs

nav:
  - 首页: index.md
  - 引脚布局: pin-layout.md
  - 树莓派专用命令: commands.md
  - GPIO 操作指南: gpio.md
  - 蓝牙配置与数据交换: bluetooth.md
  - USB 外置声卡: usb-soundcard.md
  - 传感器: sensors.md
  - 模数转换器: adc.md
  - 按键与开关模块: button.md
  - 脚本系统服务: service.md
  - 蜂鸣器: buzzer.md
  - 电机基础: motors.md
  - MG90S 舵机: servo.md
  - IR38K 红外接收: irremote.md
  - nRF24L01 无线模块: nrf24l01.md
  - SH1106 OLED 屏幕: oled.md
  - MQTT 服务器: mqtt.md
  - ESP32-CAM 模块使用: esp32cam.md
